name: Baserow Bulk vers n8n

on:
  workflow_dispatch:

jobs:
  send-domains:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run script
        env:
          BASEROW_API_URL: ${{ secrets.BASEROW_API_URL }}
          BASEROW_API_TOKEN: ${{ secrets.BASEROW_API_TOKEN }}
          BASEROW_TABLE_ID: ${{ secrets.BASEROW_TABLE_ID }}
          N8N_WEBHOOK_URL: ${{ secrets.N8N_WEBHOOK_URL }}
        run: python main.py
